// What we got wrong. Four belief -> killed -> now cards. Load-bearing copy, the
// most persuasive part of the page: it sits after calibration because the reader
// needs to know what calibration is before they can see what it caught. Copy
// verbatim from the frozen standalone (retractions R-01..R-04). Do not soften.

const CARDS = [
  {
    title: "1 · The 0.86 that hid a per-lead error near 1",
    believed: "A single 0.86 correlation against the target said the forward model was a good match.",
    killed:
      "Read per lead, the error was an nRMSE near 1. One pooled number had averaged over leads that did not match at all.",
    now: "We report per-lead error, never one pooled correlation, so an average can no longer hide a bad lead.",
  },
  {
    title: "2 · The ridge that turned out to be an artifact",
    believed: "A tight ridge between two parameters looked like a fundamental non-identifiability.",
    killed:
      "A follow-up run showed it was an artifact of the operating point, not an intrinsic property of the ECG.",
    now: "We call it a correlation, and only claim non-identifiability where it survives a cleaner run.",
  },
  {
    title: "3 · The signal to noise error that made everything look recoverable",
    believed: "Early runs made almost every parameter look recoverable from the ECG.",
    killed:
      "The observation noise had been applied at the wrong scale, a signal to noise ratio about 3000 times too high.",
    now: "With the noise floor set to an honest level, the spectrum separates cleanly into resolved and unresolved.",
  },
  {
    title: "4 · The real-ECG framing, killed by reading our own fixture",
    believed: "We framed the result as if the target were a real patient ECG.",
    killed: "Reading our own fixture showed the target was synthetic, generated by the simulator.",
    now: "We frame this as a synthetic-truth study on the simulator, never as real-ECG work.",
  },
];

function Beat({ label, text, tone }: { label: string; text: string; tone: string }) {
  return (
    <div>
      <div className={`text-[10px] font-mono uppercase tracking-wide ${tone}`}>{label}</div>
      <p className="mt-1 text-sm leading-relaxed text-zinc-300">{text}</p>
    </div>
  );
}

export default function WhatWeGotWrong() {
  return (
    <div>
      <div className="grid gap-4 lg:grid-cols-2">
        {CARDS.map((c) => (
          <div
            key={c.title}
            className="rounded-2xl border border-zinc-800 bg-zinc-900/40 p-5 space-y-4"
          >
            <h3 className="text-sm font-semibold text-zinc-100">{c.title}</h3>
            <Beat label="what we believed" text={c.believed} tone="text-zinc-500" />
            <Beat label="what killed it" text={c.killed} tone="text-rose-400" />
            <Beat label="what we believe now" text={c.now} tone="text-emerald-400" />
          </div>
        ))}
      </div>
      <p className="mt-6 text-sm text-zinc-400">
        The formal ledger of every retraction lives in the{" "}
        <a
          href="https://github.com/ricardogr07/ecg-purkinje-npe/blob/main/docs/verification-ledger.md"
          className="text-indigo-300 underline underline-offset-2 hover:text-indigo-200"
        >
          paper
        </a>
        .
      </p>
    </div>
  );
}
